/* UX SCENE CARDS - the drama pass as a required, TYPED artifact (UX_DOCTRINE.md).
   A flow is a scene: it must know who wants what, what stands in the way, and
   what turns. Every field is required - an incomplete card does not compile.
   The Sod is never a field you can state onto a screen; sodCheck records how the
   flow IMPLIES it. UxGate.res enforces coverage against the mockup's data-flow
   markers and lints the copy. */

type card = {
  flow: string, /* matches data-flow="..." in the mockup */
  want: string, /* who wants what, on this flow */
  wall: string, /* what stands in the way */
  turn: string, /* what has changed when the flow ends */
  cost: string, /* what failure costs */
  clock: string, /* why now */
  sodCheck: string, /* how the flow implies the Sod without saying it */
  exposition: string, /* where each fact teaches itself by consequence */
  heldCard: string, /* what depth stays submerged until life summons it */
}

/* The app's Sod (never stated on any screen): you are never alone with money again. */
let cards = [
  /* ---- ACT 1: onboarding (the app opens at the story's beginning) ---- */
  {
    flow: "ob-invite",
    want: "A person who has never trusted an app with money wants to know why this one is different.",
    wall: "Every fintech onboarding opens with a form and a promise; both read as the stranger talking.",
    turn: "The first screen is not software - it is Amaka, a person they have sat beside for six years.",
    cost: "Open with a wallet-signup and the driver closes the app at the motor park; the circle never forms.",
    clock: "The circle is moving to the app THIS week; the invitation expires with the round.",
    sodCheck: "The very first thing the app shows is a trusted face standing between the user and the technology.",
    exposition: "What a ROSCA is arrives as the user's OWN circle's facts (12 members, $100, Fridays), never as a definition.",
    heldCard: "Everything - pocket, tin, ring - is absent; only the invitation exists.",
  },
  {
    flow: "setup",
    want: "A new member wants to know exactly what stands between them and being a full participant.",
    wall: "Three unfamiliar acts (PIN, funding, first round) - invisible, they feel like a maze; narrated, they feel like a lecture.",
    turn: "A three-line checklist that lights up as each real act completes; done means done.",
    cost: "Without a visible path the member stalls at an empty wallet and never reaches Friday.",
    clock: "Round 6 closes Friday; the checklist exists to be finished before it.",
    sodCheck: "Every step on the list points at other people - the agent, the circle, Amaka's pot.",
    exposition: "Each row teaches only by being tappable when it becomes possible (pay unlocks after funding).",
    heldCard: "The list never mentions tin, keepers, or recovery - those wait for the surplus.",
  },
  {
    flow: "add-money",
    want: "Turn cash in a pocket into balance on the phone, right now.",
    wall: "The member's own action ends at showing a code; completion belongs to another human with the float.",
    turn: "A QR appears, an agent scans it, and the balance is simply there - no account numbers, no forms.",
    cost: "If funding needs an exchange or a bank form, the unbanked are filtered out at the door.",
    clock: "The setup list is waiting on this step; the round is due Friday.",
    sodCheck: "Even putting money IN is a two-person act across a counter.",
    exposition: "'Show this code at any agent' is the entire instruction; the waiting state says who acts next.",
    heldCard: "Rails, minting, and MUSD mechanics stay entirely beneath the QR.",
  },
  {
    flow: "bills-grid",
    want: "Do the everyday money jobs (airtime, transfer, bills) the way every Nigerian app does them.",
    wall: "A wallet that only does the circle reads as a gadget, not as money; the mode is the shell.",
    turn: "The familiar grid works (transfer, airtime live; the rest marked not-in-pilot) - this is a money app that HAPPENS to carry the circle.",
    cost: "Skip the shell and users file the app under 'crypto thing' and never trust it with real cash.",
    clock: "Airtime runs out today; the fare needs paying now.",
    sodCheck: "The everyday tier is deliberately ordinary - the circle and keepers stand out because the rest is familiar.",
    exposition: "Nothing to learn: the grid is the convention every OPay/PalmPay user already knows.",
    heldCard: "The one off-mode element (the table) hides behind an ordinary tab until tapped.",
  },
  {
    flow: "me-profile",
    want: "See yourself as the app sees you: seat, standing, keepers, what happens if you vanish.",
    wall: "Identity-and-death settings are usually buried; here they are the product's spine.",
    turn: "One screen answers seat, Fridays, PIN, keepers, and the 90-day inheritance line.",
    cost: "If the death answer is buried, the kitchen-table veto kills adoption.",
    clock: "Checked when a member weighs how much of their life to move in.",
    sodCheck: "The profile is mostly OTHER people - your keepers and your heir, not your settings.",
    exposition: "Inheritance is one plain sentence on the same card as the keepers it uses.",
    heldCard: "The machinery (shares, thresholds) stays entirely beneath the names.",
  },
  {
    flow: "cash-out",
    want: "Turn balance back into cash in the hand, at the same counter it came from.",
    wall: "Money that can't leave is a trap; the exit must be as plain as the entrance.",
    turn: "Amount, a code, an agent's scan - and cash crosses the counter the other way.",
    cost: "No visible exit and the unbanked (rightly) refuse the entrance.",
    clock: "Rent is due in naira tonight.",
    sodCheck: "The exit, like the entrance, is a human across a counter - never a form.",
    exposition: "'The agent scans it and hands you cash' is the entire manual.",
    heldCard: "Rails and float stay invisible behind the QR.",
  },
  {
    flow: "key-setup",
    want: "Give the vault a second key: enrol the card by touching it to the phone, or invite a person who signs remotely.",
    wall: "A key is hardware or a human - each needs its own ceremony (a physical tap; an invitation accepted on another phone), not a settings toggle.",
    turn: "The vault activates by arithmetic the moment two keys exist - no activate button anywhere.",
    cost: "Fake this and the security story is a sticker; users sense a lock with no key.",
    clock: "Deposits are refused until the second key exists; the surplus is waiting.",
    sodCheck: "Even the setup is other people and physical things - never the phone alone.",
    exposition: "'Hold the card against the phone' and a waiting state - the ceremony explains itself.",
    heldCard: "Key cryptography stays entirely beneath tap-and-accept.",
  },
  {
    flow: "heir-set",
    want: "Name who the vault walks to if this phone goes silent for good.",
    wall: "Death settings are usually a legal form; here it is one contact picked from the phone book.",
    turn: "From that tap on, the app shows exactly what the user configured - a name, never a narrated relationship.",
    cost: "Unset, the money dies with the phone - the oldest grief of cash and crypto alike.",
    clock: "Set while alive and calm; the reaper does not schedule.",
    sodCheck: "The answer to death is a person plus three keepers - company to the very end.",
    exposition: "One sentence at the moment of choosing: silent 90 days, three keepers confirm, it transfers.",
    heldCard: "The timer machinery stays a single quiet line until silence actually falls.",
  },
  {
    flow: "guardian-pick",
    want: "The member opening their first tin wants it safe without understanding cryptography.",
    wall: "Naming 'guardians' cold is the industry's dead end - nobody can pick five reliable strangers.",
    turn: "The keepers are simply the circle plus the son abroad - trust already priced, weights already known.",
    cost: "Picked badly (or not at all), the ring rusts and the tin is a phone alone again.",
    clock: "The surplus is in the pocket TONIGHT; the tin cannot seal without keepers.",
    sodCheck: "The answer to 'who protects your money' is a list of people who already do.",
    exposition: "'Any 3 of 5 restore you; none can touch your money' - the whole threshold scheme in two plain clauses, said at sealing time.",
    heldCard: "Share expiry and the Friday refresh stay unmentioned until the first meeting.",
  },
  {
    flow: "home-glance",
    want: "The member wants one glance to answer: am I okay, and what's next?",
    wall: "A phone screen can lie or bury; trust must be earned in two seconds.",
    turn: "They leave knowing the next beat (due Friday) - oriented, not briefed.",
    cost: "A home that needs study is a home that gets ignored; ignored money rots.",
    clock: "Opened in a taxi queue between fares - seconds, not minutes.",
    sodCheck: "The proof banner shows OTHER PEOPLE acting for one of their own (Halima restored by three neighbors) - company implied, never claimed.",
    exposition: "No 'protected' adjective; the banner is an event that happened, tappable to its scene.",
    heldCard: "Week 1 shows only pocket + ajo; the tin card exists only after the reveal.",
  },
  {
    flow: "pocket-pay",
    want: "Pay a small real thing (fuel, the kiosk) right now.",
    wall: "Only the PIN - by design the wall is low; the pocket is sized so a bad day stays small.",
    turn: "Money moved, receipt in the ledger; the member trusts speed at this tier.",
    cost: "If daily pay is slow ONCE, the app dies in the market; if limitless, a thief eats savings.",
    clock: "The fare is waiting; the pump is running.",
    sodCheck: "Nothing social intrudes at this tier - solitude HERE is what makes the guarded tiers legible.",
    exposition: "Over-pocket amounts teach tiering at the moment of refusal: 'that's tin money' routes to the vault.",
    heldCard: "The existence of tiers is discovered by hitting one, not by a tutorial.",
  },
  {
    flow: "tin-glance",
    want: "See the savings are still there, still growing.",
    wall: "Savings you can't see get doubted; savings one tap deep get spent.",
    turn: "Reassured in a glance; deposit is one tap, withdrawal is a ceremony away.",
    cost: "Doubt sends them back to cash under the floor.",
    clock: "Checked after every pot payout and every rumor of theft.",
    sodCheck: "The card names the three keepers (phone, card, Emeka) - held by several hands, said as plumbing.",
    exposition: "The 2-of-3 line sits as fact; what it MEANS is learned the first time a withdrawal asks for a second hand.",
    heldCard: "Inheritance and duress exist but are absent here; they surface in their own scenes.",
  },
  {
    flow: "circle-glance",
    want: "Standing in the ajo: who paid, who's due, when do I receive?",
    wall: "Paper ledgers live in one notebook and one memory; disputes need witnesses.",
    turn: "The member sees the whole circle's state as shared truth.",
    cost: "An unclear ledger is how circles fray and reputations burn.",
    clock: "Round 6 pays Amaka Friday; your own due date stands in the list.",
    sodCheck: "Eleven other names on one screen, each with a state - the money is communal fabric, shown not said.",
    exposition: "'Witnessed by the circle ledger' lands on the paid receipt, where witnessing just happened.",
    heldCard: "The circle's second job (recovery ring) is invisible here; Friday reveals it.",
  },
  {
    flow: "circle-contribute",
    want: "Put the $100 on the table in front of everyone - the witnessed act that keeps the seat and the name (DECIDED 2026-07-06: contributions exist ONLY at the meeting; pre-pay/escrow cut).",
    wall: "The act demands presence: the meeting, the room, eleven pairs of eyes. Outside Friday the button does not exist.",
    turn: "Your coin joins the pot in the room; the ledger records what the eyes just saw.",
    cost: "An empty seat at collection is read aloud by silence; reputation is the collateral in an ajo.",
    clock: "The meeting is NOW - the pot pays out only when all twelve have put down.",
    sodCheck: "The first money act of every week is performed INSIDE the group, never alone.",
    exposition: "'Pay your $100 - at the table' appears only when the table exists; the rule teaches itself by absence.",
    heldCard: "That these witnessed Fridays also weight recovery votes stays unsaid.",
  },
  {
    flow: "friday-refresh",
    want: "The circle wants the meeting closed clean: pot paid, shares fresh, drill run.",
    wall: "Five separate humans must each act; any stale share must show itself NOW.",
    turn: "A rusted share is caught in the room at zero cost - or all five prove fresh.",
    cost: "A dead share undetected today is a failed restore on someone's worst day.",
    clock: "The room is full NOW; next chance is next Friday.",
    sodCheck: "The drill is run BY the group FOR one member in the room that won't let her fail.",
    exposition: "'A dead share shows up NOW, when it costs nothing' rides the checklist step it describes.",
    heldCard: "The cryptography (proactive share refresh) hides entirely behind a meeting ritual.",
  },
  {
    flow: "tin-withdraw",
    want: "Take real money out of the tin for a named thing (fees, the agent).",
    wall: "The tin's own protection: wait 72h in the open, or bring a second hand.",
    turn: "The member CHOOSES their wall - time watched by five, or trust spent on one.",
    cost: "No wall and a thief drains it; a hidden wall and the member feels robbed by us.",
    clock: "School fees due Friday; the agent closes at six.",
    sodCheck: "Both paths route through other people (watchers or co-signer) - never a man alone with a lever.",
    exposition: "The paths explain themselves as offers ('free * veto-able' vs 'instant * needs a second'), not as a security lecture.",
    heldCard: "What vetoing feels like is left to the veto scene.",
  },
  {
    flow: "tin-wait",
    want: "Get the money without spending anyone's trust - let time do the work.",
    wall: "72 visible hours; five guardians watching the same clock.",
    turn: "The wait completes IN THE OPEN and the release is calm, witnessed, boring.",
    cost: "If the clock hides, it reads as the bank saying no; if it can't be stopped, a thief just waits too.",
    clock: "Started now so it lands before fees are due.",
    sodCheck: "'Five people saw it, nobody objected' - the release line is other people's silence as protection.",
    exposition: "The veto power is taught by the sentence on the running clock, not by a settings page.",
    heldCard: "Who watches and how they'd stop it stays abstract until Amaka actually does.",
  },
  {
    flow: "tin-cosign",
    want: "The money now - worth waking a second key.",
    wall: "The phone alone is refused; the card is in a drawer at home; Emeka is asleep at 2:47 AM.",
    turn: "The member weighs cost: tap plastic that wakes nobody, or spend a favor across an ocean.",
    cost: "Choose wrong and you either stall at the agent's counter or burn goodwill on a routine move.",
    clock: "The agent's counter is open now; the fee window closes.",
    sodCheck: "Even alone at a counter at midnight, the move is two-handed by construction.",
    exposition: "Emeka's 2:47 AM sits beside his name - the social price shown as a clock, never as a warning.",
    heldCard: "That guardians CAN refuse is left for the veto scene to prove.",
  },
  {
    flow: "guardian-veto",
    want: "Amaka wants to stop money she doesn't recognize leaving a neighbor's tin.",
    wall: "She must act inside the window, against the awkwardness of blocking a friend.",
    turn: "The withdrawal dies; the money never moves; the matter goes to Friday's table.",
    cost: "If her veto is soft, the protection is theater; if it's rude, guardians stop guarding.",
    clock: "The 72h window is the only time a veto exists.",
    sodCheck: "Being stopped by a neighbor IS the feature: someone was watching your money at 2 AM.",
    exposition: "'One guardian is enough, and the money never moved' arrives ON the block event.",
    heldCard: "Whether it was a thief or a misunderstanding resolves off-screen, at the meeting.",
  },
  {
    flow: "pocket-to-tin",
    want: "Sweep loose money into safety before the day eats it.",
    wall: "None - by design. Deposits never wait.",
    turn: "The asymmetry lands: in is one tap, out is a ceremony.",
    cost: "Any friction on the inbound path teaches hoarding cash instead.",
    clock: "End of shift, wad in hand, bus coming.",
    sodCheck: "Effortless GIVING to the guarded pool - trust extended without paperwork.",
    exposition: "'Deposits never wait' is the entire lesson, delivered by the toast on the act.",
    heldCard: "Nothing withheld; this flow is deliberately shallow.",
  },
  {
    flow: "recovery-glance",
    want: "Answer the 3 AM fear: if this phone dies, do I still exist?",
    wall: "The fear is abstract; five names and their freshness must beat it in one screen.",
    turn: "Fear resolves into a roster: these five, any three, last drilled Friday.",
    cost: "Unanswered, the fear keeps savings in cash under the floor.",
    clock: "Checked after every lost-phone story in the market.",
    sodCheck: "The whole screen is a LIST OF PEOPLE where other apps put a seed phrase.",
    exposition: "'Shares expire unless refreshed at the meeting' - the drill-as-protocol taught in one line of fact.",
    heldCard: "The ledger weights (214 Fridays) sit quiet under each name until a vote makes them speak.",
  },
  {
    flow: "practice-drill",
    want: "Prove the circle can rebuild me BEFORE the day I need it.",
    wall: "Three guardians must actually act, live; a stale share fails here, publicly.",
    turn: "The worst day gets a rehearsal number; recovery becomes a chore, not a cliff.",
    cost: "An undrilled ring is Sky-King cryptography: perfect math, rusted humans.",
    clock: "Drills ride the meeting; skip one and it's a month of rust.",
    sodCheck: "Three neighbors pause their Friday to rebuild YOUR key - the drill IS company.",
    exposition: "'Wipes nothing - proves the circle can put you back together' kills the fear of the button.",
    heldCard: "The real restore's gravity is preserved by keeping the drill visibly consequence-free.",
  },
  {
    flow: "lost-phone-restore",
    want: "A member with a strange phone in their hand wants their life back.",
    wall: "Three of five guardians must stand in front of them and act; grief and panic are in the room.",
    turn: "From 'it's all gone' to 'same money, new phone' - the promise kept in public.",
    cost: "THE failure mode of self-custody; fail here and the whole thesis was a lie.",
    clock: "The phone left in a taxi an hour ago; the room is assembled tonight.",
    sodCheck: "The ceremony is faces looking at your face - recovery is literally being recognized.",
    exposition: "'Nothing else was on it to steal' teaches key-share architecture inside the reassurance.",
    heldCard: "The cryptographic re-deal hides behind guardians tapping confirm.",
  },
  {
    flow: "inheritance",
    want: "Answer 'if I die, my family loses everything' while alive and calm.",
    wall: "Naming an heir stares at death; most tools make it morbid paperwork.",
    turn: "Adaeze is named and visible; the fear has a standing answer in the open.",
    cost: "Unanswered, adoption dies at the kitchen table - the spouse vetoes the app.",
    clock: "Set once, seen every visit; the reaper does not schedule.",
    sodCheck: "Even death doesn't leave the member alone with it - the circle walks the tin home.",
    exposition: "The whole mechanism is one sentence on the heir's own card, where it belongs.",
    heldCard: "The 90-day machinery stays a single quiet line until silence actually falls.",
  },
  {
    flow: "ninety-day-heir",
    want: "The circle wants a silent member's tin to reach his widow, correctly.",
    wall: "Ninety days must truly pass; three guardians must confirm to her face.",
    turn: "The dead man's savings arrive without his phone, his PIN, or his ghost.",
    cost: "Fail and the money is burned with the man - the oldest grief of cash and of crypto alike.",
    clock: "The ninetieth day fires exactly once.",
    sodCheck: "Even the final transfer is a room of his people, not a form.",
    exposition: "'Nothing needed from the dead man's pocket' states the entire architecture as one plain fact.",
    heldCard: "Runs only in simulation here; the real flow belongs to the widow's phone, another story.",
  },
]
